### ISSUE TITLE
Have this as a rack application

### ISSUE THREAD

**Issue by alexandru-calinoiu** [bradylove/wamp-ruby#2]
Hi,

I want to have this as a rack application that I can mount inside my other rack application. One scenario will be to have handle websocket requests with this app and normal http requests with a grape based api.

Do you think is a good idea, shall I send you a pull request?

**Comment by gregory** [comment]
Hey guys, just found this. I'm curious, anyone of you used this in prod? how stable/mature is this?

**Comment by balauru** [comment]
I am using it in production to send messages between desktop and mobile apps, I had no issues with it after I figured out https://github.com/puma/puma/issues/589
